### ISSUE TITLE
how to solve this problem

### ISSUE THREAD

**Issue by yangzhipeng1108** [lopentusska/slurm_ubuntu_gpu_cluster#1]
Jul 02 14:16:27 node1 systemd[1]: Starting Slurm DBD accounting daemon...
Jul 02 14:16:27 node1 systemd[392520]: slurmdbd.service: Failed to locate executable /usr/sbin/slurmdbd: No such file or directory
Jul 02 14:16:27 node1 systemd[392520]: slurmdbd.service: Failed at step EXEC spawning /usr/sbin/slurmdbd: No such file or directory
Jul 02 14:16:27 node1 systemd[1]: slurmdbd.service: Control process exited, code=exited, status=203/EXEC
Jul 02 14:16:27 node1 systemd[1]: slurmdbd.service: Failed with result 'exit-code'.
Jul 02 14:16:27 node1 systemd[1]: Failed to start Slurm DBD accounting daemon.
Jul 02 14:16:28 node1 systemd[1]: /etc/systemd/system/slurmdbd.service:11: PIDFile= references a path below legacy directory /var/run/, updating /var/run/slurmdbd.pid → /run/slurmdbd.pid; pleas>
Jul 02 14:16:28 node1 systemd[1]: /etc/systemd/system/slurmdbd.service:11: PIDFile= references a path below legacy directory /var/run/, updating /var/run/slurmdbd.pid → /run/slurmdbd.pid; pleas>
Jul 02 14:16:28 node1 systemd[1]: /etc/systemd/system/slurmdbd.service:11: PIDFile= references a path below legacy directory /var/run/, updating /var/run/slurmdbd.pid → /run/slurmdbd.pid; pleas>

**Comment by lopentusska** [comment]
try to start slurmdbd in debug mode `slurmdbd -Dvvv`
